// This file is auto-generated by Cancer. Do not edit manually.
// Run `cancer generate-types` to regenerate.

export interface HomeProps {
  title: string;
  message: string;
  user: User;
  stats: Stats;
}

export interface Stats {
  visits: number;
  likes: number;
}

export interface User {
  name: string;
  email: string;
}

