// This file is auto-generated by Ferro. Do not edit manually.
// Run `ferro generate-types` to regenerate.
// Compatible with Inertia.js v2+ UrlMethodPair interface

import type { Method } from '@inertiajs/core';

// Route configuration - compatible with Inertia's UrlMethodPair
export interface RouteConfig<TData = void> {
  url: string;
  method: Method;  // 'get' | 'post' | 'put' | 'patch' | 'delete'
  data?: TData;
}

// Path parameter types
export interface UserShowParams {
  id: string;
}

// Controller namespace - mirrors backend structure
export const controllers = {
  config_example: {
    show: (): RouteConfig => ({ url: '/config', method: 'get' })
  },
  home: {
    index: (): RouteConfig => ({ url: '/', method: 'get' }),
    protected: (): RouteConfig => ({ url: '/protected', method: 'get' })
  },
  todo: {
    list: (): RouteConfig => ({ url: '/todos', method: 'get' }),
    create_random: (): RouteConfig => ({ url: '/todos/random', method: 'post' })
  },
  user: {
    index: (): RouteConfig => ({ url: '/users', method: 'get' }),
    show: (params: UserShowParams): RouteConfig => ({ url: `/users/${params.id}`, method: 'get' }),
    store: (): RouteConfig => ({ url: '/users', method: 'post' }),
    redirect_example: (): RouteConfig => ({ url: '/redirect-example', method: 'get' })
  }
} as const;

// Named routes lookup
export const routes = {
  'home': controllers.home.index,
  'users.index': controllers.user.index,
  'users.show': controllers.user.show,
  'users.store': controllers.user.store,
  'config.show': controllers.config_example.show,
  'todos.index': controllers.todo.list,
  'todos.create_random': controllers.todo.create_random
} as const;
